version: "3.8"

services:
  my-jenkins:
    image: my-jenkins
    container_name: my-jenkins
    restart: unless-stopped

    ports:
      - "9000:8080"
      - "50000:50000"

    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - JAVA_OPTS=-Dhudson.model.DirectoryBrowserSupport.CSP="default-src 'self' 'unsafe-inline';"

    # 🔴 FIX DNS (risolve "Could not resolve host: github.com")
    dns:
      - 8.8.8.8
      - 1.1.1.1

    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-data: