pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            environment {
                HOME = '/tmp'
                GOCACHE = '/tmp/go-build'
            }
            steps {
                dir('bugtracker-backend') {
                    sh '''
                        mkdir -p $GOCACHE
                        go test -v ./...
                    '''
                }
            }
        }
    }
}
