pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Debug') {
            steps {
                sh '''
                    hostname
                    whoami
                    pwd
                    ls -la
                '''
            }
        }

        stage('Execute Unit Tests') {
            parallel {

                stage('Unit Tests - Backend') {
                    agent {
                        docker {
                            image 'golang:1.21'
                            reuseNode true
                            args '--network=host'
                        }
                    }

                    environment {
                        GOCACHE = "${WORKSPACE}/.cache/go-build"
                        GOMODCACHE = "${WORKSPACE}/.cache/go-mod"
                        GOPROXY = "https://proxy.golang.org,direct"
                    }

                    steps {
                        dir('bugtracker-backend') {
                            sh '''
                                mkdir -p $GOCACHE $GOMODCACHE

                                go install github.com/jstemmer/go-junit-report/v2@latest
                                export PATH=$PATH:$(go env GOPATH)/bin

                                go mod download
                                go test ./... -v 2>&1 | go-junit-report > test-results.xml
                            '''
                        }
                    }
                }

                stage('Unit Tests - Frontend') {
                    agent {
                        docker {
                            image 'node:20'
                            reuseNode true
                            args '--network=host'
                        }
                    }

                    steps {
                        dir('bugtracker-frontend') {
                            sh '''
                                node -v
                                npm -v
                                npm ci
                                npm test
                            '''
                        }
                    }
                }

            }
        }

        stage('Launch Application') {
            agent {
                docker {
                    image 'docker:27.5.1'
                    reuseNode true
                    args '-v /var/run/docker.sock:/var/run/docker.sock -u 0'
                }
            }
            steps {
                sh 'docker compose up --build -d'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}